tectijuana/tallerdb

- resources/tutorials/tips/33-Protege datos con CHECK en restricciones.md
ALUMNO:PADRON JIMENEZ NICOL JHAMYLETD 
NO. CONTROL: 22211629
33-Protege datos con CHECK en restricciones_(Asegura que los valores insertados cumplan ciertas condiciones.)
> 33-Protege datos con CHECK en restricciones.md

- resources/tutorials/tips/14-Implementa FULL OUTER JOIN para todas las filas.md
Realice la contribución del tip 14
> TIP-14-Implementa FULL OUTER JOIN para todas las filas.

- 13-Usa RIGHT JOIN para mantener datos derechos.md
Devuelve todas las filas de la tabla derecha con coincidencias opcionales.
> 13 - Usa RIGHT JOIN para mantener datos derechos.md

- resources/tutorials/tips/44-Calcula promedios con AVG.md
Alumno: Brian Guadalupe Tellez Escobar C21211400
Se realizo:
Calcula promedios con AVG | Devuelve el promedio de los valores en una columna numérica.
> Create 44-Calcula promedios con AVG.md

- resources/tutorials/tips/1-Usa_las_CTEs_(Expresiones_Tabla_Común).md
- resources/tutorials/tips/2-Maneja valores nulos con COALESCE.md
Concorde a la tabla de tips, se realizo lo siguiente:
C22211401	1-2	revisar, ordenas los temas 1 y 2 generados por el docente, agregar su nombre
Muchas gracias!
> Trabajo de Estudiante Urrea Gonzalez Fernando Andre 

- resources/tutorials/tips/27-Convierte valores con CAST y CONVERT.md
Contribución America Martinez Perez
> Tip 27 - Convierte valores con CAST y CONVERT

- resources/tutorials/tips/34-Manejo de Claves Foráneas con `FOREIGN KEY`.md
Profe aquí esta mi contribución y el material listo que me toco, gracias por los tips y herramientas para facilitarnos el trabajo gracias maestro. :)
> Create 34-Manejo de Claves Foráneas con `FOREIGN KEY`.md

- resources/tutorials/tips/24-Usa DEFAULT para valores predefinidos.md
> 24-Usa DEFAULT para valores predefinidos.md

- resources/tutorials/tips/37- Usa REPLACE para actualizar o insertar filas.md
Ramirez  Guerra Marcos Yeran, Este es el trabajo
> 37- Usa REPLACE para actualizar filas

- resources/tutorials/tips/39-Encuentra valores extremos con MIN y MAX.md
JORDHY JAIR ROJAS OSUNA 22210349
Obtén el valor más pequeño o grande de una columna numérica o de texto.
> 39-Encuentra valores extremos con MIN y MAX.md

- resources/tutorials/tips/12-Utiliza LEFT JOIN para incluir datos faltantes.md
Utiliza LEFT JOIN para incluir datos faltantes
> 12-Utiliza LEFT JOIN para incluir datos faltantes

- resources/tutorials/tips/26-Concatena cadenas con CONCAT.md
> Create 26-Concatena cadenas con CONCAT

- assignments/U1/sqlzoo.net/nobel/GUAF272004/readme.md
Se crearon los elementos pedidos en las instrucciones de la practica, al igual que el codigo de los problemas del premio noble y sus explicaciones para cada uno de estos.
> Creacion de Readme.md y Carpeta con Nickname

- assignments/U1/sqlzoo.net/nobel/BrianTz79/readme.md
Se realizaron las practicas de SQL en la pagina de SQLZoo
> Actividad Nobel BrianTZ79

- assignments/U1/sqlzoo.net/nobel/Zer0M4n/readme.md
agrege la soslucion y cambie el directorio, lamento las molestias
> 22211575-NOBEL

- assignments/U1/sqlzoo.net/nobel/americamtzp/readme.md
America martinez perez practica consultas
> trabajo sqlzoo.net

- assignments/U1/sqlzoo.net/selectDeselect/americamtzp/readme.md
Practica select a select America Martinez Perez #21211991
> SELECT DE SELECT practica

- assignments/U1/sqlzoo.net/selectDeselect/gashetas06/readme.md
SELECT within SELECT Tutorial, SQLZoo.net
> SELECT within SELECT

- assignments/U1/sqlzoo.net/selectDeselect/CastelanITT/readme.md
> 22211589 - Select - Juarez Castelan Jose

- assignments/U1/sqlzoo.net/selectDeselect/DanielSuarezNieto/Readme.md
> Select de Select 22210356 - Readme.md

- assignments/U1/sqlzoo.net/selectDeselect/Rother22/Readme.md
---
Le entrego la actividad de SelectDeselect, algo tarde pero no podía enviarla porque tenia ya un pull request abierto y no quería eliminarlo o no entendía como.
---
> SelectDeselect actividad 
